x-redis-replica-config: &redis-replica-config
  image: redis:6.2
  command: ["redis-server", "--slaveof", "redis-master", "6379"]
  depends_on:
    - redis-master
  networks:
    - webnet

x-redis-sentinel-config: &redis-sentinel-config
  image: redis:6.2
  command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  depends_on:
    - redis-master
  networks:
    - webnet

services:
  web:
    image: alraro/practica2-software-critico:1.1.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    environment:
      - REDIS_HOST=redis
      - PORT=5000
    networks:
      - webnet
    depends_on:
      - sentinel-1
      - sentinel-2
      - sentinel-3

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - redis-master
    networks:
      - webnet
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource

  redis-master:
    image: redis:6.2
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis_sentinel/master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - webnet

  redis-replica-1:
    <<: *redis-replica-config
    container_name: redis-replica-1

  redis-replica-2:
    <<: *redis-replica-config
    container_name: redis-replica-2

  sentinel-1:
    <<: *redis-sentinel-config
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./redis_sentinel/sentinels/sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel-2:
    <<: *redis-sentinel-config
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./redis_sentinel/sentinels/sentinel2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel-3:
    <<: *redis-sentinel-config
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./redis_sentinel/sentinels/sentinel3.conf:/usr/local/etc/redis/sentinel.conf

volumes:
  grafana_data:

networks:
  webnet:
